### ISSUE TITLE
/archives pulling from analysis.php instead of index.php

### ISSUE THREAD

**Issue by jnschrag** [CSIS-iLab/amti_2016#32] opened 2016-09-20 13:59 UTC
The [archives page](http://amti2016.staging.wpengine.com/archives/) is set up to be the site's latest posts page. The latest posts page should be pulling from `home.php` or `index.php`.

On my local environment, the archive page is properly pulling from `index.php`. On the staging site, it's pulling from `analysis.php` instead.

**Comment by pkfranz** [comment] 2016-09-20 18:43
found old `home.php`, made it a dupe of `index.php` should we need to customize further later

**Closed** 2016-09-20 18:43 UTC
Labels: bug
